### PR TITLE
fix data-race in setTextureData (fixes #1257)

### LINKED ISSUE #1257: ThreadSanitizer(testRunner_v5.js): data race @rtRef.h:70 in rtImageResource::setTextureData(pxOffscreen&, char const*, unsigned long)
Detected by: https://semaphoreci.com/dwrobel/pxcore/branches/onemw-wayland-egl-47/builds/53

```
WARNING: ThreadSanitizer: data race (pid=8769)
  Read of size 8 at 0x7b4800002390 by thread T2 (mutexes: write M68815477845816920):
    #0 rtRef<pxTexture>::asn(pxTexture const*) /home/runner/pxCore/examples/pxScene2d/src/../../../src/rtRef.h:70 (pxscene+0x476a9d)
    #1 rtRef<pxTexture>::operator=(rtRef<pxTexture> const&) /home/runner/pxCore/examples/pxScene2d/src/../../../src/rtRef.h:59 (pxscene+0x476a9d)
    #2 rtImageResource::setTextureData(pxOffscreen&, char const*, unsigned long) /home/runner/pxCore/examples/pxScene2d/src/pxResource.cpp:369 (pxscene+0x476a9d)
    #3 rtImageResource::loadResourceData(rtFileDownloadRequest*) /home/runner/pxCore/examples/pxScene2d/src/pxResource.cpp:568 (pxscene+0x47961b)
    #4 pxResource::processDownloadedResource(rtFileDownloadRequest*) /home/runner/pxCore/examples/pxScene2d/src/pxResource.cpp:600 (pxscene+0x477227)
    #5 pxResource::onDownloadComplete(rtFileDownloadRequest*) /home/runner/pxCore/examples/pxScene2d/src/pxResource.cpp:555 (pxscene+0x476d2a)
    #6 rtFileDownloadRequest::executeCallback(int) /home/runner/pxCore/src/rtFileDownloader.cpp:244 (pxscene+0x523795)
    #7 rtFileDownloader::downloadFile(rtFileDownloadRequest*) /home/runner/pxCore/src/rtFileDownloader.cpp:612 (pxscene+0x526a7a)
    #8 startFileDownloadInBackground(void*) /home/runner/pxCore/src/rtFileDownloader.cpp:132 (pxscene+0x526dc4)
    #9 rtThreadTask::execute() /home/runner/pxCore/src/rtThreadTask.cpp:38 (pxscene+0x50b742)
    #10 rtThreadPoolNative::startThread() /home/runner/pxCore/src/unix/rtThreadPoolNative.cpp:105 (pxscene+0x503bbd)
    #11 launchThread(void*) /home/runner/pxCore/src/unix/rtThreadPoolNative.cpp:27 (pxscene+0x503cbc)
    #12 <null> <null> (libtsan.so.0+0x29d3d)

  Previous write of size 8 at 0x7b4800002390 by main thread (mutexes: write M68252493531849624):
    #0 rtRef<pxTexture>::asn(pxTexture const*) /home/runner/pxCore/examples/pxScene2d/src/../../../src/rtRef.h:77 (pxscene+0x476811)
    #1 rtRef<pxTexture>::operator=(pxTexture const*) /home/runner/pxCore/examples/pxScene2d/src/../../../src/rtRef.h:58 (pxscene+0x476811)
    #2 rtImageResource::getTexture(bool) /home/runner/pxCore/examples/pxScene2d/src/pxResource.cpp:330 (pxscene+0x476811)
    #3 rtImageResource::setupResource() /home/runner/pxCore/examples/pxScene2d/src/pxResource.cpp:382 (pxscene+0x4768fb)
    #4 pxResource::onDownloadCompleteUI(void*, void*) /home/runner/pxCore/examples/pxScene2d/src/pxResource.cpp:441 (pxscene+0x476514)
    #5 rtThreadQueue::process(double) /home/runner/pxCore/src/rtThreadQueue.cpp:77 (pxscene+0x50a745)
    #6 pxScene2d::onUpdate(double) /home/runner/pxCore/examples/pxScene2d/src/pxScene2d.cpp:2449 (pxscene+0x4a7b27)
    #7 pxScriptView::onUpdate(double) /home/runner/pxCore/examples/pxScene2d/src/pxScene2d.h:1251 (pxscene+0x4c256f)
    #8 sceneWindow::onAnimationTimer() /home/runner/pxCore/examples/pxScene2d/src/pxScene.cpp:387 (pxscene+0x5031f3)
    #9 pxWindowNative::onAnimationTimerInternal() /home/runner/pxCore/src/wayland_egl/pxWindowNative.cpp:496 (pxscene+0x506654)
    #10 pxWindowNative::animateAndRender() /home/runner/pxCore/src/wayland_egl/pxWindowNative.cpp:863 (pxscene+0x507593)
    #11 pxWindowNative::runEventLoop() /home/runner/pxCore/src/wayland_egl/pxWindowNative.cpp:602 (pxscene+0x507a8f)
    #12 pxEventLoop::run() /home/runner/pxCore/src/wayland_egl/pxEventLoopNative.cpp:35 (pxscene+0x508c56)
    #13 pxMain(int, char**) /home/runner/pxCore/examples/pxScene2d/src/pxScene.cpp:679 (pxscene+0x5020e4)
    #14 main /home/runner/pxCore/src/wayland_egl/pxEventLoopNative.cpp:50 (pxscene+0x473ffe)

  Location is heap block of size 336 at 0x7b4800002280 allocated by main thread:
    #0 operator new(unsigned long) <null> (libtsan.so.0+0x7502a)
    #1 pxImageManager::getImage(char const*, char const*, int, int) /home/runner/pxCore/examples/pxScene2d/src/pxResource.cpp:753 (pxscene+0x478639)
    #2 pxImage9::setUrl(char const*) /home/runner/pxCore/examples/pxScene2d/src/pxImage9.cpp:84 (pxscene+0x49a187)
    #3 pxImage9::setUrl_PropSetterThunk(rtValue const&) /home/runner/pxCore/examples/pxScene2d/src/pxImage9.h:31 (pxscene+0x49b0e3)
    #4 rtObject::Set(char const*, rtValue const*) /home/runner/pxCore/src/rtObject.cpp:450 (pxscene+0x570f9e)
    #5 pxObject::Set(char const*, rtValue const*) /home/runner/pxCore/examples/pxScene2d/src/pxScene2d.cpp:685 (pxscene+0x4a5c80)
    #6 rtObjectRef::Set(char const*, rtValue const*) /home/runner/pxCore/src/rtObject.cpp:614 (pxscene+0x570b9c)
    #7 rtObjectBase::set(char const*, rtValue const&) /home/runner/pxCore/src/rtObject.h:87 (pxscene+0x571bb0)
    #8 rtObjectBase::set(rtObjectRef) /home/runner/pxCore/src/rtObject.cpp:481 (pxscene+0x571bb0)
    #9 pxScene2d::createImage9(rtObjectRef, rtObjectRef&) /home/runner/pxCore/examples/pxScene2d/src/pxScene2d.cpp:2128 (pxscene+0x4bad32)
    #10 pxScene2d::create(rtObjectRef, rtObjectRef&) /home/runner/pxCore/examples/pxScene2d/src/pxScene2d.cpp:2022 (pxscene+0x4bfb50)
    #11 pxScene2d::create_thunk(int, rtValue const*, rtValue&) /home/runner/pxCore/examples/pxScene2d/src/pxScene2d.h:1300 (pxscene+0x4e1359)
    #12 rtObjectFunction::Send(int, rtValue const*, rtValue*) /home/runner/pxCore/src/rtObject.cpp:630 (pxscene+0x570eaa)
    #13 rtScriptNodeUtils::rtFunctionWrapper::call(v8::FunctionCallbackInfo<v8::Value> const&) /home/runner/pxCore/src/rtScriptNode/rtFunctionWrapper.cpp:252 (pxscene+0x548cea)
    #14 v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) <null> (libnode8-shared.so.57+0x6f3059)
    #15 uv__queue_done <null> (pxscene+0x5de57e)
    #16 rtScript::pump() /home/runner/pxCore/src/rtScript.cpp:221 (pxscene+0x52b9bc)
    #17 sceneWindow::onAnimationTimer() /home/runner/pxCore/examples/pxScene2d/src/pxScene.cpp:393 (pxscene+0x5031ff)
    #18 pxWindowNative::onAnimationTimerInternal() /home/runner/pxCore/src/wayland_egl/pxWindowNative.cpp:496 (pxscene+0x506654)
    #19 pxWindowNative::animateAndRender() /home/runner/pxCore/src/wayland_egl/pxWindowNative.cpp:863 (pxscene+0x507593)
    #20 pxWindowNative::runEventLoop() /home/runner/pxCore/src/wayland_egl/pxWindowNative.cpp:602 (pxscene+0x507a8f)
    #21 pxEventLoop::run() /home/runner/pxCore/src/wayland_egl/pxEventLoopNative.cpp:35 (pxscene+0x508c56)
    #22 pxMain(int, char**) /home/runner/pxCore/examples/pxScene2d/src/pxScene.cpp:679 (pxscene+0x5020e4)
    #23 main /home/runner/pxCore/src/wayland_egl/pxEventLoopNative.cpp:50 (pxscene+0x473ffe)

  Mutex M68815477845816920 is already destroyed.

  Mutex M68252493531849624 is already destroyed.

  Thread T2 (tid=8772, running) created by main thread at:
    #0 pthread_create <null> (libtsan.so.0+0x2c3f2)
    #1 rtThreadPoolNative::initialize() /home/runner/pxCore/src/unix/rtThreadPoolNative.cpp:53 (pxscene+0x503e45)
    #2 rtThreadPoolNative::rtThreadPoolNative(int) /home/runner/pxCore/src/unix/rtThreadPoolNative.cpp:35 (pxscene+0x504227)
    #3 rtThreadPool::rtThreadPool(int) /home/runner/pxCore/src/rtThreadPool.cpp:31 (pxscene+0x50a140)
    #4 __static_initialization_and_destruction_0 /home/runner/pxCore/src/rtThreadPool.cpp:28 (pxscene+0x47418f)
    #5 _GLOBAL__sub_I_rtThreadPool.cpp /home/runner/pxCore/src/rtThreadPool.cpp:50 (pxscene+0x47418f)
    #6 __libc_csu_init <null> (pxscene+0x5f9414)

SUMMARY: ThreadSanitizer: data race /home/runner/pxCore/examples/pxScene2d/src/../../../src/rtRef.h:70 in rtRef<pxTexture>::asn(pxTexture const*)
```

### PR DESCRIPTION
**Pull request by dwrobel**

### CODE REVIEW

**Comment by dwrobel** [comment]
It might be simpler/better protect the whole rtImageResource::setTextureData() by mTextureMutex.lock(); but, I'm not sure about the following:
>rtThreadTask* task = new rtThreadTask(prepareImageResource, (void*)this, "");
>  textureCreateThreadPool.executeTask(task);

File: examples/pxScene2d/src/pxResource.cpp [hunk 1]
```diff
@@ -366,7 +366,9 @@ void rtImageResource::prepare()
 
 void rtImageResource::setTextureData(pxOffscreen& imageOffscreen, const char* data, const size_t dataSize)
 {
+  mTextureMutex.lock();
```
Comment (mfiess) [inline examples/pxScene2d/src/pxResource.cpp]: Is this lock needed?  I think the code prevents mDownloadedTexture from being accessed by multiple threads at the same time without a mutex.

Comment (dwrobel) [reply examples/pxScene2d/src/pxResource.cpp]: It's a fix for #1257 - please have a look at the second frame in the two first backtraces:

(1)
>#2 rtImageResource::setTextureData(pxOffscreen&, char const*, unsigned long) /home/runner/pxCore/examples/pxScene2d/src/pxResource.cpp:369 (pxscene+0x476a9d)

(2)
>#2 rtImageResource::getTexture(bool) /home/runner/pxCore/examples/pxScene2d/src/pxResource.cpp:330 (pxscene+0x476811)

both accessing `mDownloadedTexture` but only `getTexture()`  in (2) is using `mTextureMutex` while `setTextureData()` doesn't seem to use it.
